image: python:3.5-slim-buster

stages:
  - build
  - test
  - deploy

lint:
  stage: build
  script:
    - python -m pip install flake8
    - flake8 --max-line-length=120 .

py35:unit-tests:
  stage: test
  script:
    - python -m pip install -r requirements-dev.txt
    - pytest --show-capture=no --cov --cov-fail-under=50
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'   # Execute jobs when a new commit is pushed to master branch
    - if: $CI_MERGE_REQUEST_ID            # Execute jobs in merge request context

pypi:deploy:
  stage: deploy
  script:
    # Build and Deploy to PyPI
    # Install sphinx to have rst2html.py utility available
    - python -m pip install sphinx twine
    - |
      if [ "$(./get_pypi_latest_version.sh)" != "$(python setup.py --version)" ]
      then
        # Check that the long description is ready to be published on PyPI without errors
        python setup.py --long-description | rst2html.py > /dev/null 2>error.log
        if [ ! "$(cat error.log)" ]
        then
          # Build the distribution
          python setup.py sdist bdist_wheel
          twine upload dist/*
        else
          echo "Long description is incompatible with PyPI reST renderer. Check README.rst"
          cat error.log
          exit 1
        fi
      else
        echo "Current version is the latest version uploaded to PyPI"
        exit 1
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+.*/'
